{{- if eq .Values.database.dataStore "SqlServer" }}{{- if not (empty .Values.database.sql.existing) }}
{{- $fullName := include "fhir-server.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
type: Opaque
data:
  fullyQualifiedServerName: {{ .Values.database.sql.existing.serverName | b64enc | quote }}
  username: {{ .Values.database.sql.existing.username | b64enc | quote }}
  password: {{ .Values.database.sql.existing.password | b64enc | quote }}
{{- end }}{{- end }}